// Code generated by goagen v1.5.13, DO NOT EDIT.
//
// API "test_build": Application Media Types
//
// Command:
// $ goagen
// --design=github.com/kod-source/docker-goa-mysql/design
// --out=/Users/horikoudai/program-practice/docker-goa/app
// --version=v1.5.13

package app
