// Code generated by goagen v1.5.13, DO NOT EDIT.
//
// API "test_build": Application User Types
//
// Command:
// $ goagen
// --design=github.com/kod-source/Docker-Goa-Air/design
// --out=/Users/horikoudai/Documents/ProgrammingLearning/Docker-Goa-Air/app
// --version=v1.5.13

package client
