consumes:
- application/json
- application/xml
- application/gob
- application/x-gob
definitions:
  Url:
    description: A tenant account (default view)
    example:
      amount: 300
      id: 1
    properties:
      amount:
        description: API href of amount
        example: 300
        format: int64
        type: integer
      id:
        description: ID of account
        example: 1
        format: int64
        type: integer
    required:
    - id
    title: 'Mediatype identifier: application/vnd.url+json; view=default'
    type: object
host: localhost:3000
info:
  description: A teaser for goa
  title: The adder API
  version: ""
paths:
  /add/{left}/{right}:
    get:
      description: add returns the sum of the left and right parameters in the response
        body
      operationId: test#add
      parameters:
      - description: Left operand
        in: path
        name: left
        required: true
        type: integer
      - description: Right operand
        in: path
        name: right
        required: true
        type: integer
      produces:
      - text/plain
      responses:
        "200":
          description: OK
        "404":
          description: Not Found
      schemes:
      - http
      summary: add test
      tags:
      - test
  /url/{left}/{middle}/{right}:
    get:
      description: add returns the sum
      operationId: url#url_add
      parameters:
      - description: Left operand
        in: path
        name: left
        required: true
        type: integer
      - description: Middle operand
        in: path
        name: middle
        required: true
        type: integer
      - description: Right operand
        in: path
        name: right
        required: true
        type: integer
      produces:
      - application/vnd.url+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Url'
        "404":
          description: Not Found
      schemes:
      - http
      summary: url_add url
      tags:
      - url
produces:
- application/json
- application/xml
- application/gob
- application/x-gob
responses:
  NotFound:
    description: Not Found
schemes:
- http
swagger: "2.0"
